export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'
export const CURRENT_PAGE_SET = 'CURRENT_PAGE_SET'
export const SET_PAGE_LOADING = 'SET_PAGE_LOADING'

// COURSE
export const COURSES_LOADED = 'COURSES_LOADED'
export const COURSE_LOADED = 'COURSE_LOADED'

// ADMIN
export const ADMIN_CLIENTS_LOADED = 'ADMIN_CLIENTS_LOADED'
export const ADMIN_CLEINT_LOADED = 'ADMIN_CLEINT_LOADED'
export const CLIENT_FOR_CHAT_LOADED = 'CLIENT_FOR_CHAT_LOADED'

// CLIENT
export const CLIENT_ADMIN_LOADED = 'CLIENT_ADMIN_LOADED'
export const CLIENTS_LOADED = 'CLIENTS_LOADED'
export const CLIENT_LOADED = 'CLIENT_LOADED'

// MESSAGE
export const MESSAGES_LOADED = 'MESSAGES_LOADED'
export const CLIENTS_MESSAGE_NUMBERS_LOADED = 'CLIENTS_MESSAGE_NUMBERS_LOADED'
export const ADMIN_UNREAD_MESSAGES_LOADED = 'ADMIN_UNREAD_MESSAGES_LOADED'
export const CLIENT_UNREAD_MESSAGES_LOADED = 'CLIENT_UNREAD_MESSAGES_LOADED'

// EXAM RESULTS
export const EXAM_RESULTS_LOADED = 'EXAM_RESULTS_LOADED'
export const EXAM_RESULT_LOADED = 'EXAM_RESULT_LOADED'